@startuml

title __HELPERS's Class Diagram__\n

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace helpers {
          class org.openapi2puml.openapi.plantuml.helpers.PlantUMLClassHelper {
              {static} - CARDINALITY_NONE_TO_MANY : String
              {static} - CARDINALITY_ONE_TO_MANY : String
              - includeCardinality : boolean
              {static} - logger : Logger
              + PlantUMLClassHelper()
              + processSwaggerModels()
              - convertModelPropertiesToClassMembers()
              - getChildClasses()
              - getClassMember()
              - getClassMember()
              - getClassMember()
              - getClassMembers()
              - getClassMembers()
              - getClassMembers()
              - getClassMembers()
              - getClassMembers()
              - getDataType()
              - getEnum()
              - getRefClassMembers()
              - getSuperClass()
              - isModelClass()
              - isRequiredProperty()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace helpers {
          class org.openapi2puml.openapi.plantuml.helpers.PlantUMLInterfaceDiagramHelper {
              {static} - logger : Logger
              + processSwaggerPaths()
              - filterUnique()
              - getErrorClass()
              - getErrorClassNames()
              - getInterfaceDiagram()
              - getInterfaceMethods()
              - getInterfaceName()
              - getInterfaceRelatedInputs()
              - getInterfaceRelatedResponses()
              - getInterfaceRelations()
              - getInterfaceReturnType()
              - getMethodParameters()
              - isTargetClassInMap()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace helpers {
          class org.openapi2puml.openapi.plantuml.helpers.PlantUMLRelationHelper {
              + getRelations()
              - filterUnique()
              - getAllInterfacesRelations()
              - getAllModelRelations()
              - isTargetClassInMap()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
