@startuml

title __PLANTUML's Class Diagram__\n

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        class org.openapi2puml.openapi.plantuml.FormatUtility {
            {static} + toTitleCase()
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        class org.openapi2puml.openapi.plantuml.MustacheUtility {
            {static} - LOGGER : Logger
            + createPlantUmlFile()
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        class org.openapi2puml.openapi.plantuml.PlantUMLCodegen {
            {static} ~ CLASS_DIAGRAMS : String
            {static} ~ ENTITY_RELATIONS : String
            {static} ~ INTERFACE_DIAGRAMS : String
            {static} ~ TITLE : String
            {static} ~ VERSION : String
            {static} - LOGGER : Logger
            - generateDefinitionModelOnly : boolean
            - includeCardinality : boolean
            - swagger : Swagger
            - targetLocation : File
            + PlantUMLCodegen()
            + convertSwaggerToPlantUmlObjectModelMap()
            + generatePlantUmlFile()
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        class org.openapi2puml.openapi.plantuml.PlantUMLGenerator {
            {static} - LOGGER : Logger
            + PlantUMLGenerator()
            + transformOpenApi2Puml()
            - generateUmlDiagramFile()
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
