@startuml

title __VO's Class Diagram__\n

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace vo {
          class org.openapi2puml.openapi.plantuml.vo.ClassDiagram {
              - childClasses : List<ClassRelation>
              - className : String
              - description : String
              - fields : List<ClassMembers>
              - isClass : boolean
              - superClass : String
              + ClassDiagram()
              + ClassDiagram()
              + getChildClass()
              + getClassName()
              + getDescription()
              + getFields()
              + getSuperClass()
              + isClass()
              + setChildClass()
              + setClass()
              + setClassName()
              + setDescription()
              + setFields()
              + setSuperClass()
              + toString()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace vo {
          class org.openapi2puml.openapi.plantuml.vo.ClassMembers {
              - cardinality : String
              - className : String
              - dataType : String
              - name : String
              + ClassMembers()
              + ClassMembers()
              + getCardinality()
              + getClassName()
              + getDataType()
              + getName()
              + setCardinality()
              + setClassName()
              + setDataType()
              + setName()
              + toString()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace vo {
          class org.openapi2puml.openapi.plantuml.vo.ClassRelation {
              - cardinality : String
              - isComposition : boolean
              - isExtension : boolean
              - sourceClass : String
              - targetClass : String
              + ClassRelation()
              + ClassRelation()
              + getCardinality()
              + getSourceClass()
              + getTargetClass()
              + isComposition()
              + isExtension()
              + setCardinality()
              + setComposition()
              + setExtension()
              + setSourceClass()
              + setTargetClass()
              + toString()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace vo {
          class org.openapi2puml.openapi.plantuml.vo.InterfaceDiagram {
              - childClasses : List<ClassRelation>
              - errorClasses : List<String>
              - interfaceName : String
              - methods : List<MethodDefinitions>
              + InterfaceDiagram()
              + InterfaceDiagram()
              + getChildClass()
              + getErrorClasses()
              + getInterfaceName()
              + getMethods()
              + setChildClass()
              + setErrorClasses()
              + setInterfaceName()
              + setMethods()
              + toString()
          }
        }
      }
    }
  }
  

  namespace org.openapi2puml {
    namespace openapi {
      namespace plantuml {
        namespace vo {
          class org.openapi2puml.openapi.plantuml.vo.MethodDefinitions {
              - methodDefinition : String
              - returnType : String
              + MethodDefinitions()
              + MethodDefinitions()
              + getMethodDefinition()
              + getReturnType()
              + setMethodDefinition()
              + setReturnType()
              + toString()
          }
        }
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
